### ISSUE TITLE
ArrayIndexOutOfBoundsException when opening in browser

### ISSUE THREAD

**Issue by robinhowlett** [sdeleuze/spring-react-isomorphic#1]
Using java version "1.8.0_45"

After running `gradle clean installApp -x javadoc` (to get the `output` directory created) on the cmd line and refreshing in IDE, starting via IsomorphicApplication main method works and app starts.

However, when opening localhost:8080 throws the following:

```
2015-05-01 07:25:57.000 ERROR 19966 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: failed to render template] with root cause

java.lang.ArrayIndexOutOfBoundsException: 9
    at java.lang.invoke.MethodHandleImpl$ArrayAccessor.getElementL(MethodHandleImpl.java:130)
    at jdk.nashorn.internal.scripts.Script$Recompilation$302$560196AA$\^eval\_.L:4-1$L:18234$instantiateReactComponent(<eval>:18333)
    at jdk.nashorn.internal.scripts.Script$Recompilation$376$147092AAA$\^eval\_.L:4-1$L:4696$instantiateChildren(<eval>:4739)
    at jdk.nashorn.internal.scripts.Script$Recompilation$375$396568AAA$\^eval\_.L:4-1$L:12623$mountChildren(<eval>:12804)
    at jdk.nashorn.internal.scripts.Script$Recompilation$374$236403AA$\^eval\_.L:4-1$L:7396$_createContentMarkup(<eval>:7683)
    at jdk.nashorn.internal.scripts.Script$Recompilation$356$234184AAA$\^eval\_.L:4-1$L:7396$mountComponent(<eval>:7593)
    at jdk.nashorn.internal.scripts.Script$Recompilation$349$434323AAAA$\^eval\_.L:4-1$L:14034$mountComponent(<eval>:14072)
    at jdk.nashorn.internal.scripts.Script$Recompilation$309$195650AAA$\^eval\_.L:4-1$L:6158$mountComponent(<eval>:6399)
    at jdk.nashorn.internal.scripts.Script$Recompilation$308$413782AAA$\^eval\_.L:4-1$L:13301$measure$wrapper(<eval>:13371)
    at jdk.nashorn.internal.scripts.Script$Recompilation$349$434323AAAA$\^eval\_.L:4-1$L:14034$mountComponent(<eval>:14072)
    at jdk.nashorn.internal.scripts.Script$Recompilation$375$396568AAA$\^eval\_.L:4-1$L:12623$mountChildren(<eval>:12815)
    at jdk.nashorn.internal.scripts.Script$Recompilation$374$236403AA$\^eval\_.L:4-1$L:7396$_createContentMarkup(<eval>:7683)
    at jdk.nashorn.internal.scripts.Script$Recompilation$356$234184AAA$\^eval\_.L:4-1$L:7396$mountComponent(<eval>:7593)
    at jdk.nashorn.internal.scripts.Script$Recompilation$349$434323AAAA$\^eval\_.L:4-1$L:14034$mountComponent(<eval>:14072)
    at jdk.nashorn.internal.scripts.Script$Recompilation$309$195650AAA$\^eval\_.L:4-1$L:6158$mountComponent(<eval>:6399)
    at jdk.nashorn.internal.scripts.Script$Recompilation$308$413782AAA$\^eval\_.L:4-1$L:13301$measure$wrapper(<eval>:13371)
    at jdk.nashorn.internal.scripts.Script$Recompilation$349$434323AAAA$\^eval\_.L:4-1$L:14034$mountComponent(<eval>:14072)
    at jdk.nashorn.internal.scripts.Script$Recompilation$309$195650AAA$\^eval\_.L:4-1$L:6158$mountComponent(<eval>:6399)
    at jdk.nashorn.internal.scripts.Script$Recompilation$308$413782AAA$\^eval\_.L:4-1$L:13301$measure$wrapper(<eval>:13371)
    at jdk.nashorn.internal.scripts.Script$Recompilation$349$434323AAAA$\^eval\_.L:4-1$L:14034$mountComponent(<eval>:14072)
    at jdk.nashorn.internal.scripts.Script$Recompilation$375$396568AAA$\^eval\_.L:4-1$L:12623$mountChildren(<eval>:12815)
    at jdk.nashorn.internal.scripts.Script$Recompilation$374$236403AA$\^eval\_.L:4-1$L:7396$_createContentMarkup(<eval>:7683)
    at jdk.nashorn.internal.scripts.Script$Recompilation$356$234184AAA$\^eval\_.L:4-1$L:7396$mountComponent(<eval>:7593)
    at jdk.nashorn.internal.scripts.Script$Recompilation$349$434323AAAA$\^eval\_.L:4-1$L:14034$mountComponent(<eval>:14072)
    at jdk.nashorn.internal.scripts.Script$Recompilation$309$195650AAA$\^eval\_.L:4-1$L:6158$mountComponent(<eval>:6399)
    at jdk.nashorn.internal.scripts.Script$Recompilation$308$413782AAA$\^eval\_.L:4-1$L:13301$measure$wrapper(<eval>:13371)
    at jdk.nashorn.internal.scripts.Script$Recompilation$349$434323AAAA$\^eval\_.L:4-1$L:14034$mountComponent(<eval>:14072)
    at jdk.nashorn.internal.scripts.Script$Recompilation$309$195650AAA$\^eval\_.L:4-1$L:6158$mountComponent(<eval>:6399)
    at jdk.nashorn.internal.scripts.Script$Recompilation$308$413782AAA$\^eval\_.L:4-1$L:13301$measure$wrapper(<eval>:13371)
    at jdk.nashorn.internal.scripts.Script$Recompilation$301$440790AAAAAA$\^eval\_.L:4-1$L:14258$renderToString$L:14297(<eval>:14300)
    at jdk.nashorn.internal.scripts.Script$Recompilation$294$511743AAAAAAAA$\^eval\_.L:4-1$L:16491$perform(<eval>:16625)
    at jdk.nashorn.internal.scripts.Script$Recompilation$286$440389A$\^eval\_.L:4-1$L:14258$renderToString(<eval>:14297)
    at jdk.nashorn.internal.scripts.Script$Recompilation$281$48AA$\^eval\_#1\!6653\^eval\_.process(<eval>#1:6653<eval>:40)
    at jdk.nashorn.internal.scripts.Script$Recompilation$279$1754AA$\^eval\_.L:1$render(<eval>:1)
    at jdk.nashorn.internal.scripts.Script$Recompilation$260$33AA$\^eval\_.render(<eval>:13)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
    at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:192)
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:381)
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:187)
    at org.springframework.web.servlet.view.script.ScriptTemplateView.renderMergedOutputModel(ScriptTemplateView.java:137)
    at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by thomasdarimont** [comment]
Hi,

I see the same exception with Java 1.8.0_40 / 45.

The problem seems to be in the render.js.

if I use `data[k] = []` instead of `data[k] = Java.from(model[k]);` I can browse the index page with the two default comments listed. I can also add new comments -> SSE work fine :)

Perhaps this helps hunting down the actual problem...

Cheers,
Thomas

**Comment by pepez** [comment]
I would say this is a bug in Java 8 Nashorn. Something changed since update 25 as update 40/45/51 do not work.

**Comment by sdeleuze** [comment]
I am going to update this app now than both Spring 4.2.0 and Java 8u60 are available. I will make a feedback here shortly.

**Comment by sdeleuze** [comment]
With the latest update (see commit https://github.com/sdeleuze/spring-react-isomorphic/commit/95ec13a9b2f028ed3008703cf37e36142a94c0cc) and Java 8 update 60, the application seems to run fin, even with `gradle bootRun`.

Nashorn bundled with Java 1.8.0_40 / 45 has several issues, so I think that was the problem.

Could someone confirm that it works well now?

**Comment by thomasdarimont** [comment]
Hi,

I can confirm that it works with:

```
tom@euler ~/dev/repos/gh/thomasdarimont/spring-react-isomorphic (master) 
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

Thanks Sebastien :)

Cheers,
Thomas

**Comment by sdeleuze** [comment]
Thanks Thomas :-)

**Comment by robinhowlett** [comment]
Thanks everyone!
