### ISSUE TITLE
Does not work with React 0.14.0

### ISSUE THREAD

**Issue by aantono** [sdeleuze/spring-react-isomorphic#3]
After an attempted upgrade to use `org.webjars:react:0.14.0` the application fails with the following exception upon attempting to load the page:

```
[dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Failed to render script template] with root cause
jdk.nashorn.internal.runtime.ECMAException: TypeError: Cannot call undefined
    at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98) ~[nashorn.jar:na]
    at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176) ~[nashorn.jar:na]
    at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:na]
    at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154) ~[nashorn.jar:na]
    at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253) ~[nashorn.jar:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$283$639042AAAAAA$\^eval\_.L:4-1$L:18700$warning(<eval>:18745) ~[na:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$282$550475A$\^eval\_.L:4-1$L:15896$deprecated$newFn(<eval>:15928) ~[na:na]
    at jorn.internal.scripts.Script$Recompilation$277$48AA$\^eval\_#1\!6653\^eval\_.process(<eval>#1:6653<eval>:25) ~[na:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$275$1754AA$\^eval\_.L:1$render(<eval>:1) ~[na:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$255$33AA$\^eval\_.render(<eval>:3) ~[na:na]
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:644) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228) ~[nashorn.jar:na]
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:na]
    at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199) ~[nashorn.jar:na]
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383) ~[nashorn.jar:na]
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190) ~[nashorn.jar:na]
    at org.springframework.web.servlet.view.script.ScriptTemplateView.renderMergedOutputModel(ScriptTemplateView.java:294) ~[spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
    at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303) ~[spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
```

**Comment by aantono** [comment]
Looks like adding `console.error = print;` to `polyfill.js` seems to fix this problem.

**Comment by wlepinski** [comment]
@aantono :+1: worked for me.
